# Generated by Django 5.2.8 on 2025-11-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pittrain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitairporttrainfact',
            name='ranking',
            field=models.TextField(blank=True),
        ),
    ]
